import Currency from '../../../../shared/account-currency';
import Budget from './budget/budget.model';
import categories from '../../categories/category-list/categories-list';

const BudgetData: Budget[] = [
  {
    id: '1',
    category: categories[0],
    amountAvailable: 2500,
    currency: Currency.RON,
    amountSpent: 2000,
    startDate: new Date('2024-04-03'),
    resetDate: new Date('2024-05-03'),
    active: true,
  },
  {
    id: '2',
    category: categories[1],
    amountAvailable: 1000,
    currency: Currency.RON,
    amountSpent: 800,
    startDate: new Date('2024-04-01'),
    resetDate: new Date('2022-05-01'),
    active: true,
  },
  {
    id: '3',
    category: categories[2],
    amountAvailable: 600,
    currency: Currency.RON,
    amountSpent: 500,
    progress: 100,
    startDate: new Date('2024-03-31'),
    resetDate: new Date('2022-04-30'),
    active: true,
  },
  {
    id: '4',
    category: categories[3],
    amountAvailable: 500,
    currency: Currency.RON,
    amountSpent: 350,
    startDate: new Date('2024-03-30'),
    resetDate: new Date('2022-04-29'),
    active: true,
  },
  {
    id: '5',
    category: categories[4],
    amountAvailable: 300,
    currency: Currency.RON,
    amountSpent: 200,
    startDate: new Date('2024-03-29'),
    resetDate: new Date('2022-04-28'),
    active: true,
  },
  {
    id: '6',
    category: categories[5],
    amountAvailable: 500,
    currency: Currency.RON,
    amountSpent: 400,
    startDate: new Date('2024-03-28'),
    resetDate: new Date('2022-04-27'),
    active: true,
  },
  {
    id: '7',
    category: categories[6],
    amountAvailable: 400,
    currency: Currency.RON,
    amountSpent: 300,
    startDate: new Date('2024-03-27'),
    resetDate: new Date('2022-04-26'),
    active: true,
  },
  {
    id: '8',
    category: categories[7],
    amountAvailable: 300,
    currency: Currency.RON,
    amountSpent: 120,
    startDate: new Date('2024-03-26'),
    resetDate: new Date('2022-04-25'),
    active: true,
  },
];

export default BudgetData;
