import Currency from '../../../../shared/account-currency';
import CashTransaction from './cash-transaction.model';
import { categories } from '../../categories/category-list/categories-list';

const CashTransactions: CashTransaction[] = [
  {
    id: 'm5gr84i9',
    type: 'expense',
    beneficiary: 'Mega Image',
    details: 'Mancare',
    amount: 316,
    currency: Currency.RON,
    postingDate: new Date('2024-04-01'),
    category: categories[1],
    status: 'success',
  },
  {
    id: '3u1reuv4',
    type: 'expense',
    beneficiary: 'Petrom',
    details: 'Benzina',
    amount: 242,
    currency: Currency.RON,
    postingDate: new Date('2024-04-02'),
    category: categories[2],
    status: 'success',
  },
  {
    id: 'derv1ws0',
    type: 'expense',
    beneficiary: 'Farmacia Tei',
    details: 'Medicamente',
    amount: 837,
    currency: Currency.RON,
    postingDate: new Date('2024-04-04'),
    category: categories[4],
    status: 'processing',
  },
  {
    id: '5kma53ae',
    type: 'expense',
    beneficiary: 'Dedeman',
    details: 'Mobila',
    amount: 874,
    currency: Currency.RON,
    postingDate: new Date('2024-03-01'),
    category: categories[0],
    status: 'success',
  },
  {
    id: 'bhqecj4p',
    type: 'expense',
    beneficiary: 'Altex',
    details: 'Laptop',
    amount: 3200,
    currency: Currency.RON,
    postingDate: new Date('2024-04-08'),
    category: categories[3],
    status: 'failed',
  },
  {
    id: 'p0r8sd2f',
    type: 'expense',
    beneficiary: 'Flanco',
    details: 'Televizor',
    amount: 1000,
    currency: Currency.RON,
    postingDate: new Date('2024-02-01'),
    category: categories[3],
    status: 'failed',
  },
  {
    id: '8uyv3n1x',
    type: 'expense',
    beneficiary: 'Lidl',
    details: 'Mancare',
    amount: 589,
    currency: Currency.RON,
    postingDate: new Date('2024-04-10'),
    category: categories[1],
    status: 'processing',
  },
  {
    id: '2zqo6ptr',
    type: 'expense',
    beneficiary: 'Proprietar',
    details: 'Chirie',
    amount: 456,
    currency: Currency.RON,
    postingDate: new Date('2024-04-01'),
    category: categories[0],
    status: 'success',
  },
  {
    id: 'l7we9a3m',
    type: 'expense',
    beneficiary: 'Mega Image',
    details: 'Mancare',
    amount: 100,
    currency: Currency.RON,
    postingDate: new Date('2024-04-12'),
    category: categories[1],
    status: 'success',
  },
  {
    id: 'o9p2v3qk',
    type: 'expense',
    beneficiary: 'Petrom',
    details: 'Benzina',
    amount: 200,
    currency: Currency.RON,
    postingDate: new Date('2024-04-19'),
    category: categories[2],
    status: 'failed',
  },
  {
    id: 'q1o8r7mz',
    type: 'expense',
    beneficiary: 'Asociatia de Proprietari',
    details: 'Intretinere',
    amount: 321,
    currency: Currency.RON,
    postingDate: new Date('2024-04-01'),
    category: categories[0],
    status: 'processing',
  },
  {
    id: 'i5n3s0tv',
    type: 'expense',
    beneficiary: 'Dedeman',
    details: 'Birou',
    amount: 400,
    currency: Currency.RON,
    postingDate: new Date('2024-04-19'),
    category: categories[0],
    status: 'failed',
  },
  {
    id: '3xr7s2nl',
    type: 'expense',
    beneficiary: 'Enel',
    details: 'Abonament Curent',
    amount: 220,
    currency: Currency.RON,
    postingDate: new Date('2024-04-05'),
    category: categories[10],
    status: 'success',
  },
  {
    id: 'u9v2p1qy',
    type: 'expense',
    beneficiary: 'Digi',
    details: 'Abonament Internet',
    amount: 45,
    currency: Currency.RON,
    postingDate: new Date('2024-04-02'),
    category: categories[10],
    status: 'success',
  },
  {
    id: 'b4q0e1cp',
    type: 'expense',
    beneficiary: 'Vodafone',
    details: 'Abonament Telefon',
    amount: 40,
    currency: Currency.RON,
    postingDate: new Date('2024-04-01'),
    category: categories[10],
    status: 'failed',
  },
  {
    id: 's1z8m7op',
    type: 'income',
    beneficiary: 'Viva Credit',
    details: 'Salariu',
    amount: 6600,
    currency: Currency.RON,
    postingDate: new Date('2024-04-10'),
    category: categories[8],
    status: 'success',
  },
  {
    id: 'n5a3v0lt',
    type: 'income',
    beneficiary: 'Revolut',
    details: 'Cripto',
    amount: 121.12,
    currency: Currency.RON,
    postingDate: new Date('2024-04-18'),
    category: categories[9],
    status: 'failed',
  },
  {
    id: '2qr7v9sm',
    type: 'income',
    beneficiary: 'Iulia',
    details: 'Datorie',
    amount: 650,
    currency: Currency.RON,
    postingDate: new Date('2024-04-13'),
    category: categories[7],
    status: 'processing',
  },
  {
    id: 'y9b2h8qq',
    type: 'expense',
    beneficiary: 'Mega Image',
    details: 'Cumparaturi',
    amount: 56.25,
    currency: Currency.RON,
    postingDate: new Date('2024-04-10'),
    category: categories[1],
    status: 'success',
  },
  {
    id: 'c4a0r1xp',
    type: 'expense',
    beneficiary: 'Petrom',
    details: 'Benzina',
    amount: 120,
    currency: Currency.RON,
    postingDate: new Date('2024-04-14'),
    category: categories[2],
    status: 'failed',
  },
];

export default CashTransactions;
